---
title: "Session_9: Using prettydoc package and introduction to R"
author: "Ahmad Mutaher"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##Introduction
"- R is a well-known computer language used for graphical display and statistical computation. 
 - Data analysis and visualization are its most popular applications.
 - It is a fantastic resource for data science, machine learning, data analysis, and data visualization.
 - It offers a variety of statistical methods (such as statistical tests, classification, clustering and data reduction)
 - Drawing graphs in R is simple and includes creating histograms, box plots, scatter plots, and pie charts.
 - It functions across several platforms (Windows, Mac, Linux)
 - It is free and open-source.
 - It enjoys widespread community support."

##Imports libraries
library("here")
library("tidyverse")
library("tidytuesdayR")
library("ymlthis")
library("prettydoc")

##testing plot
DataCoffee <- read.csv("https://raw.githubusercontent.com/jldbc/coffee-quality-database/master/data/arabica_ratings_raw.csv")


plotCountry <- DataCoffee %>%
               select(quality_score,Country.of.Origin,Owner,Company,Number.of.Bags,Moisture) %>%
               filter(quality_score > 87)

               ggplot(plotCountry, aes(x=Owner, y=Country.of.Origin)) +
               geom_bar(stat="identity", width=0.2) +
               coord_flip()  
                
plotround <-DataCoffee %>%
            select(quality_score,Country.of.Origin,Owner,Company,Number.of.Bags,Moisture,Company)%>%
            filter(quality_score > 87 & !is.na(DataCoffee$Company))
            
            ggplot(plotround,aes(x =quality_score , fill = Company) ) +
            geom_bar() +
            coord_polar(theta = "y") +
            scale_x_discrete("")
                
PlotFacet <-DataCoffee %>%
            select(quality_score,Country.of.Origin,Owner,Company,Number.of.Bags,Moisture,Company)%>%
            filter(quality_score > 88 & !is.na(DataCoffee$Company))              
            
            ggplot(PlotFacet,aes(x = quality_score, fill = Company) ) +
            geom_bar() + 
            facet_grid( ~ Company)   

Plotpoint <-DataCoffee %>%
            select(quality_score,Country.of.Origin,Owner,Company,Number.of.Bags,Moisture,Company)%>%
            filter(quality_score > 88)              
            
            ggplot(Plotpoint,aes(x = Country.of.Origin, y= Company) ) +
            geom_point() +
            coord_flip()
##End of Document           
              
                          
              
              
      


```

